### PR TITLE
Add description to repo

### PR DESCRIPTION
**Pull request by patcon**
Adding descriptions to EDGI repos could help orient new people to our codebases

@patcon -- are you able to add a description for this repo?

### CODE REVIEW

**Comment by patcon** [comment]
@dcwalk weird that the issue started by you was renamed to be mine when converted to PR...

**Comment by dcwalk** [comment]
I feel like I've missed a few steps about why we're adopting probot configurator? Can you point me in the direction of the conversation?

**Comment by patcon** [comment]
Sorry, there's no prior conversation -- it adds something that allows any code contributor to change settings for the repo via pull request, and brings those sorts of changes into pull request flow. (Probot is an official github tool, so it's their space to add certain sorts of functionality now)

Do you feel we should give this a larger conversation?

**Comment by patcon** [comment]
bump

**Comment by dcwalk** [comment]
Hmmm @patcon these didn't sync?

**Comment by patcon** [comment]
Ah, I hadn't actually enabled it on this repo, pending a thumbs up for using it..! Should have had this in a "todo" section. Enabled now, and I'll push a no-op commit to master to sync it

**Pull request merged**
