### PR TITLE
Add chatbot command to upload zoom recordings to youtube

### PR DESCRIPTION
**Pull request by patcon**
Add command to upload recorded videos from zoom to youtube. This seems like more autonomy than auto-uploading every night.

```
alice: @halpy zoom youtube upload
halpy: Queuing all recorded videos to upload to EDGI's YouTube account as unlisted videos.
       When complete, videos will be added to this unlisted playlist:
       https://www.youtube.com/playlist?list=PLtsP3g9LafVv78TIa42xr591-4CfKMYQO
```

Once this is done, would be nice to perhaps add other commands if people want more control:
1. ability to list existing zoom recordings
2. ability to upload specific recording instead of all

Blocked by https://github.com/edgi-govdata-archiving/overview/issues/149, which will provide an API for running [existing script](https://github.com/edgi-govdata-archiving/edgi-scripts#zoom-youtube-uploader) that I manually run.

## To Do

- [x] Write bot command to poke jenkins server (see [access doc](https://paper.dropbox.com/doc/Services-Deployment-pTsHUVIb2JuFHo8KVfpq2)) and run the video upload script on demand (currently runs nightly)

### CODE REVIEW

**Comment by patcon** [comment]
OK, so here is the current flow:

```
bob: let's start a meeting
alice: good call
alice: @halpy zoom me rec now Our meeting
halpy: alice started a recorded zoom session: https://edgi-video-call-landing-page.herokuapp.com/https://zoom.us/j/555555555
```
when the meeting ends
```
alice: that was a great meeting that we just finished right now!
alice: @halpy zoom youtube upload
halpy: Ok, sure thing! I've just kicked off upload of Zoom videos to YouTube. If any videos are uploaded, I'll drop a message in #meeting_announcements on EDGI Slack when it's done!
```
Alice goes to check `#meeting_announcements` and sees this:

```
halpy: A user initiated upload of Zoom videos to YouTube, but at least one video was still processing. Please wait 5 minutes and try again.
```

If she waits 5 minutes and tries again, she'll see this in `#meeting_announcements` instead:
```
halpy: New meeting video(s) have been uploaded! https://www.youtube.com/playlist?list=PLtsP3g9LafVv78TIa42xr591-4CfKMYQO
```

-----------------
Notes:
- we avoid dropping playlist link in channel of original halpy command, because that link is semi-privileged, and we wouldn't want to leave it in bridged channels like `#webmonitoring`

**Comment by patcon** [comment]
Yeesh... You're right @Mr0grog... I suppose I was thinking cron nightly, and then thinking manual for sooner, but very little reason not to run every 15 minutes... except maybe giving people a chance to "fix" something that was accidentally said, before putting it on youtube...

But I think every 15 minutes would be fine, given that the playlist in unlisted anyhow

@dcwalk thoughts?

**Comment by Mr0grog** [comment]
Oh, did not consider the case where something needs to be bleeped or cut out. Whatever is appropriate.

**Comment by dcwalk** [comment]
We (I've done some manual cutting 2-3 times total (basically a completely unrelated convo before/after, once _someone elses_ completely unreated convo).

I don't think it has ever been a huge concern, and could be handled post hoc, so running quite frequently isn't an issue in my mind!

Sorry, the last few weeks kind of destroyed my notifications, only now wading back through.

**Comment by dcwalk** [comment]
In terms of the flow, I would just imagine halpy talking to themselves a bunch:
`halpy: I've just kicked off upload of Zoom videos to YouTube. If any videos are uploaded, I'll drop a message in #meeting_announcements on EDGI Slack when it's done!`

**Comment by patcon** [comment]
Ok, going to close this and open another for just the simple little router endpoint that will help halpy notify :)

**Comment by patcon** [comment]
We're now running this on circleci, which is building nightly.

We could create a small script to rerun the most recent build for a project, using these endpoints:

- https://circleci.com/docs/api/v1-reference/#recent-builds-project-branch
- https://circleci.com/docs/api/v1-reference/#retry-build

**Comment by patcon** [comment]
We're now running this on circleci, which is building nightly.

We could create a small script to rerun the most recent build for a project, using these endpoints:

- https://circleci.com/docs/api/v1-reference/#recent-builds-project-branch
- https://circleci.com/docs/api/v1-reference/#retry-build

**Pull request closed without merging**
